FROM mhart/alpine-node:10 as front
ENV TZ="Europe/Amsterdam"
# install missing alpine packages
RUN apk add --update git openssh
WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN ls -al
RUN npm run build

# stage 2
FROM nginx:latest
EXPOSE 3333
# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*
# COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=front /frontend/build /usr/share/nginx/html
# copy only static files of the react app

CMD ["nginx", "-g", "daemon off;"]
RUN echo "\e[104mAfter running the docker container the frontend will start at: localhost:80\e[0m\n\n"

# to run the frontend container manually:
# docker build -t development_frontend -f ./Dockerfile.dev .

# to see the logs you can either just run:
# docker run --name=tg-frontend -p 3000:80 development_frontend
# OR:
# docker run -d --name=tg-frontend -p 3000:80 development_frontend
# docker attach tg-frontend