FROM mhart/alpine-node:10 as front
# install missing dependencies
RUN apk add --update git openssh
COPY package.json package-lock.json ./frontend/
WORKDIR /frontend
RUN npm install
COPY . .
# CMD ["npm", "start"]
RUN npm run build
# remove node_modules?

FROM nginx:latest
EXPOSE 80
# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*
# COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=front /frontend/build /usr/share/nginx/html
# copy only static files of the react app

CMD ["nginx", "-g", "daemon off;"]
# docker build -t production_frontend -f ./Dockerfile.dev .
# docker run -p 3000:80 production_frontend