FROM mhart/alpine-node:10 as back
COPY package.json package-lock.json ./backend/
WORKDIR /backend
RUN npm install
RUN npm install pm2@3.5.1 -g
COPY . .
# remove node_modules?

# Show current folder structure in logs
RUN ls -al

# FROM nginx:latest
# EXPOSE 80
# # Remove default nginx website
# RUN rm -rf /usr/share/nginx/html/*
# # COPY nginx.conf /etc/nginx/nginx.conf
# COPY --from=back /frontend/build /usr/share/nginx/html
# # copy only static files of the react app
# CMD ["nginx", "-g", "daemon off;"]


# RUN npm run start
# CMD ["pm2-runtime", "pm2.config.js"]
CMD ["pm2-runtime", "start", "pm2.config.js", "start", "server.js", "--web", "9000"]
# CMD ["pm2-runtime", "monit"]


# docker build -t production_backend -f ./Dockerfile.dev .
# docker run -p 8080:8080 -d --name tg-backend production_backend

## https://github.com/keymetrics/docker-pm2
## https://pm2.keymetrics.io/docs/usage/deployment/
# docker exec -it tg-backend pm2 monit