FROM mhart/alpine-node:10 as back
ENV TZ="Europe/Amsterdam"
WORKDIR /backend
COPY package*.json ./
RUN npm install
RUN npm install pm2@3.5.1 -g
COPY . .

# Show current folder structure in logs
RUN ls -al


CMD ["pm2-runtime", "start", "pm2.config.js", "start", "server.js", "--web", "9000"]
RUN echo "\e[104mAfter running the docker container the frontend will start at: http://localhost:8080\e[0m\n\n"

# to run the server container manually:
# docker build -t development_backend -f ./Dockerfile.dev .
# docker run -p 8080:8080 -d --name tg-backend development_backend

## https://github.com/keymetrics/docker-pm2
## https://pm2.keymetrics.io/docs/usage/deployment/
# docker exec -it tg-backend pm2 monit