FROM mhart/alpine-node:10 as back
COPY package.json package-lock.json ./backend/
WORKDIR /backend
RUN npm install
RUN npm install pm2@3.5.1 -g
COPY . .
# remove node_modules?

# Show current folder structure in logs
RUN ls -al


CMD ["pm2-runtime", "start", "pm2.config.js", "start", "server.js", "--web", "9000"]

# docker build -t production_backend -f ./Dockerfile.dev .
# docker run -p 8080:8080 -d --name tg-backend production_backend

## https://github.com/keymetrics/docker-pm2
## https://pm2.keymetrics.io/docs/usage/deployment/
# docker exec -it tg-backend pm2 monit