export const GET_POSTS = 'dash/GET_POSTS'
export const FETCHING = 'dash/FETCHING'
export const FETCHING_END = 'dash/FETCHING_END'
export const ADD_TAG = 'dash/ADD_TAG'
export const REMOVE_TAG = 'dash/REMOVE_TAG'
export const OPEN_MODAL = 'dash/OPEN_MODAL'
export const CLOSE_MODAL = 'dash/CLOSE_MODAL'
export const SET_CURRENT_ID = 'dash/SET_CURRENT_ID'
